added travis batch
mpicbg-scicomp/gearshifft pull request #125
Opened 2018-08-23 13:38 UTC by psteinb

2018-08-23 14:15 UTC, psteinb commented
@tdd11235813 commit 97e5964 fixes a bug in the cmake setup of the tests, is it ok to keep it inside this PR?

2018-08-23 14:20 UTC, tdd11235813 commented
yes I am fine with it, thanks for the fixing :)

2018-08-23 15:22 UTC, psteinb commented
travis shows green light ... @tdd11235813 can you review & merge please?

2018-08-23 17:30 UTC, tdd11235813 requested changes
- as you are already working on it, can you rename to `GEARSHIFFT_FFTW_USE_THREADS` as described in the comment to test/test_fftw.cpp?
- for final merge it might be better to squash to a single commit, how do you think? 
  - General idea would be, if a PR works on orthogonal features, then corresponding orthogonal commits are fine (or better as separated PRs)

2018-08-23 17:30 UTC, tdd11235813 commented on test/test_fftw.cpp
> +#if defined(GEARSHIFFT_FFTW_THREADS) && GEARSHIFFT_FFTW_THREADS==1
shouldn't it be `GEARSHIFFT_FFTW_USE_THREADS` ?

2018-08-23 17:30 UTC, tdd11235813 commented on test/test_fftw.cpp
> +#if defined(GEARSHIFFT_FFTW_THREADS) && GEARSHIFFT_FFTW_THREADS==1
I mean, it should be consistent. The change was because `GEARSHIFFT_FFTW_USE_THREADS` sounds better for a boolean variable (otherwise one might think, it contains the number of threads).

2018-08-24 07:45 UTC, psteinb commented on test/test_fftw.cpp
> +#if defined(GEARSHIFFT_FFTW_THREADS) && GEARSHIFFT_FFTW_THREADS==1
the macro was called `GEARSHIFFT_FFTW_THREADS` in the c++ side. So I was sticking to this to not screw up other code. Bute sure thing, I'll make it consistent.

2018-08-24 08:40 UTC, psteinb commented
I applied the change. Feel free to do a squash and merge. I am personally more in favor of more atomic commits than monolithic commits. Atomic commits (1 feature, 1 file) support bisecting problems better, I believe.

2018-08-25 10:51 UTC, tdd11235813 commented
you are right, it is better to keep commits as small as possible to ease bug identification. 
Commits also should represent a feature or entity (commits as a unit of change), where such a commit can span over multiple files. I also think of code refactoring as an example (renaming or changing a recurrent pattern). 
The advantage would be, that there is a more clean history and features are easy to identify and to revert (and rebasing/merging might become easier).

A commit should be self-contained and in a compilable state, where possible (otherwise it should be mentioned in the description with e.g. WIP). 
For example, the last 3 commits above are dependent and represent one feature, so it should be one commit. The other commits seem to be standalone, so they could remain. 

Conclusion: Squashing all into one commit can be too coarse, and creating commits on a per-file mapping can make too much noise, i.e., the unit of change is not visible, neither in the PR nor in the commit level.

For big commits I keep my local develop branch verbose and create a PR with a cleaned up branch. Of course, it is not long-term safe, because other developers might do not have access to this verbose branch anymore. 

This would be a good compromise in my opinion, how do you think?

2018-08-28 14:19 UTC, psteinb commented
feel free to squash-merge

2018-08-31 16:51 UTC, tdd11235813 approved these changes

2018-08-31 16:52 UTC, tdd11235813 commented
merged (squashed last 3 commits).
Thanks!

2018-08-31 16:52 UTC, closed without merging